# Site settings
author: Ikaquan Bessee
title: 
header-img: img/home-bg.png
email: ikaquanbessee@yahoo.com
copyright_name: Ikaquan Bessee
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Besseeboy0947

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
